<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inventory</name>
   <tag></tag>
   <elementGuidId>feeba3ac-7133-4d2e-b2fc-a5a22d1f5802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result_app_2 > div.o_caption.w-100.text-center.text-truncate.mt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='result_app_2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Inventory&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f21c2e4f-990b-457a-b67c-1e53f62a1ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_caption w-100 text-center text-truncate mt-2</value>
      <webElementGuid>4522a588-31d4-4f59-baef-7c05b7c88f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventory</value>
      <webElementGuid>42e5d1ca-1f35-4a19-b353-0908f12867b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result_app_2&quot;)/div[@class=&quot;o_caption w-100 text-center text-truncate mt-2&quot;]</value>
      <webElementGuid>4052139c-0e3a-45f4-b266-bf7d190a3350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='result_app_2']/div</value>
      <webElementGuid>a68d59c4-adeb-4be5-b880-c6bd84afb4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[2]</value>
      <webElementGuid>8b204921-fc6a-412f-a776-11e545e339b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discuss'])[1]/following::div[4]</value>
      <webElementGuid>639fa92c-d616-4225-b0f6-a67a7b7e5c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/preceding::div[1]</value>
      <webElementGuid>d3b1109e-c3c4-4a56-aaa6-b995a8e36322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div</value>
      <webElementGuid>a6332847-f373-4f90-89c0-f0eef45f0859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inventory' or . = 'Inventory')]</value>
      <webElementGuid>e984b988-bf97-482a-8026-9efc2b0e4863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
